### ISSUE TITLE
mix meditate doesn't work with intellij

### ISSUE THREAD

**Issue by jkbbwr** [elixirkoans/elixir-koans#138]
After closing the project, installing `inotify-tools` and running `mix meditate` it doesn't detect any file changes from intellij

**Comment by cliche818** [comment]
I had to actually turn off safe write in IntelliJ (Appearance & Behavior > System Settings > Synchronization > check off Use "safe write".  

My fix didn't really help as after a few edits, the watcher will fail to reload the right file.

It seems IntelliJ write temp files like
/elixir-koans/lib/koans/03_sigils.ex___jb_old___
/elixir-koans/lib/koans/03_sigils.ex___jb_tmp___

And it writes multiple times when I edit a file which I think causes the watcher to not keep up.

**Comment by jkbbwr** [comment]
This is not uncommon. Is there a way this can be tracked and fixed.

**Comment by jkbbwr** [comment]
Thanks very much!

**Comment by leapingfrogs** [comment]
@cliche818 - I'm not experiencing the issue you mention in not keeping up with edits, but I'm curious whether that was impacted by reloading for all files not just the .ex files.  Would filtering the jb_tmp file suffix as in #156 help at all?

**Comment by iamvery** [comment]
Looks like #156 fixes the reload detection problem in IntelliJ. I guess we'll give @jkbbwr a couple days to confirm, and we'll close out this issue. Thanks everyone! ❤️

**Comment by cliche818** [comment]
@leapingfrogs Doesn't seem to help, I am using the latest version of IntelliJ with the save write checked to try this out.  Same thing happens as before.  It does reload a few times, but then it dies.  Sometimes, it even says Code.LoadError could not load [the file I just changed].

**Comment by iamvery** [comment]
@cliche818 you mentioned above both "jb_tmp" and "jb_old" files being generated. The "normalize" solution only accounts for "tmp" files. Do you think that might be related?

**Comment by jkbbwr** [comment]
yea reload aint working

**Comment by felipesere** [comment]
@jkbbwr @cliche818 can you tell me a bit more about your setup?
I am running `mix meditate` in iTerm and editing the files in IntelliJ and it seems happy.
Oh and all of this is in OSX.

I just pushed an update the helped the reload in Ubuntu. Maybe that solved it?

**Comment by jkbbwr** [comment]
Seems to magically fix it for me.
`Linux devbox2 4.9.8-1-ARCH #1 SMP PREEMPT Mon Feb 6 12:59:40 CET 2017 x86_64 GNU/Linux`
`IDEA 2017.1 EAP`

**Comment by cliche818** [comment]
Works for me on OSX, but not when I am on Windows 7 64bit.   I am using IntelliJ IDEA 2016.3.4.

**Comment by felipesere** [comment]
Grrr... I'll have to test this on a Windows box to debug.

**Comment by felipesere** [comment]
@cliche818 can you try again with latest `master`? We have updated some dependencies.

And, I may have access to a Windows box debug this. Could tell me a bit about your setup @cliche818 ? What do I need to configure and how are you actually running `mix meditate`?

**Comment by cliche818** [comment]
@felipesere Still the same as before, tried on IntelliJ IDEA 2016.3.6 first then 2017.1 since I needed to update my IDE.  It's Windows 7 64bit.  

Just went to elixir-lang.org and got the installer for Windows.  I am using elixir version 1.3.2, I haven't updated in like half a year, doubt it matters for this bug.  I just use the window's command prompt to run mix meditate.

**Comment by felipesere** [comment]
Any movement on this?

**Comment by felipesere** [comment]
This has been resolved as we have @caspg changes in our tree.
