### ISSUE TITLE
Handle unary failures more elegantly

### ISSUE THREAD

**Issue by iamvery** [elixirkoans/elixir-koans#144]
Currently failures for assertions such as `assert match?(1,2)` are displayed as if they're being made on binary statements. Here's an example:

```
Now meditate upon PatternMatching
|==>                           | 7 of 73
----------------------------------------
The pattern can make assertions about what it expects
Assertion failed in lib/koans/12_pattern_matching.ex:49
match?([1, _second, _third], [1])

left:  :ex_unit_no_meaningful_value
right: [1]
```

This unfortunately leaks ExUnit's `:ex_unit_no_meaningful_value` detail through and causes confusion (see #143) to learners.

I believe the solution would be to handle these so-called "unary" (i.e. one argument) assertions different than so-called "binary" assertions.

If I have some time to look at it I will. Just reporting this issue in case it goes to someone else ❤️

**Comment by felipesere** [comment]
This sounds interesting! Go for it :)
