### ISSUE TITLE
(Mix) Unable to find package version fs 2.12.0 in registry

### ISSUE THREAD

**Issue by amacgregor** [elixirkoans/elixir-koans#159]
Getting the following error: 

$ mix deps.get                                      
Running dependency resolution...
** (Mix) Unable to find package version fs 2.12.0 in registry

Running elixir 1.4.0

**Comment by iamvery** [comment]
This is probably related to #158. I see 2.12.0 [on Hex](https://hex.pm/packages/fs). What version of Hex do you have?

```
» mix hex.info
Hex:    0.15.0
Elixir: 1.4.0
OTP:    19.2

Built with: Elixir 1.3.4 and OTP 18.3.4.4
```

**Comment by amacgregor** [comment]
my version:

```
Hex:    0.15.0
Elixir: 1.4.0
OTP:    19.2

Built with: Elixir 1.3.4 and OTP 18.3.4.4
```

**Comment by amacgregor** [comment]
Figure it out it was a caching issue on my end, Try nuking "~/.hex/cache.ets" did the trick.

**Comment by iamvery** [comment]
Great! I haven't seen that myself before, but it's a good one to remember. Seems like something that shouldn't happen..
