### ISSUE TITLE
Nested Dictionary Structures

### ISSUE THREAD

**Issue by srufle** [elixirkoans/elixir-koans#161]
I am working my way through "Programming Elixir 1.3"
Chapter 8 - Nested Dictionary Structures
http://bit.ly/2kgQ5si

Uses get_in, put_in, update_in, and get_and_update_in. Should I modify one of the existing koans [maps, map_sets, structs]? or create a new one.

**Comment by felipesere** [comment]
Welcome!
I'd suggest extending the existing koan. Make sure to also fill in the right test 😄

**Comment by srufle** [comment]
Thx, 
How does maps_koans_test.exs relate to 09_maps.ex
How do I run tests.

**Comment by felipesere** [comment]
`09_maps.ex` are the actual koans that the user will run.
`maps_koans_test.exs` are the answers to the koans and a function to feed the answers - in the same order! - to the koans.

So if you add a new koan somewhere in the middle, you'll have to add the answer in the same position in the `answers` list.

You can run all tests by running `mix test`
