### ISSUE TITLE
mix meditate is not reloading files

### ISSUE THREAD

**Issue by glappen** [elixirkoans/elixir-koans#164]
Hello-

I am running the koans (I checked out master from git) and when I run mix meditate, then edit a koan file, it does not re-run the koans.  I am on ubuntu 16.04, i installer elixir from erlang solutions ppa, and also installed inotify-tools using apt.  Any suggestions how to debug?  Thanks!

**Comment by felipesere** [comment]
Hmm, I think we can start by adding a `--verbose` flag to give more details as to what is going on.
Let me see if I can put something together 😄

**Comment by DavidOliver** [comment]
I'm using Ubuntu 16.10 with inotify-tools installed and am finding the same.

Thanks for elixir-koans! :smiley:

**Comment by felipesere** [comment]
@DavidOliver and @glappen can you try with `master`? We have updated some dependencies.

**Comment by DavidOliver** [comment]
Definitely better. I'm finding that when saving with gedit I often have to hit Ctrl+S a couple of times for meditate to update, but when saving with Atom meditate updates on every save. Thanks!
