### ISSUE TITLE
The "unordered MapSet" koan is very unclear

### ISSUE THREAD

**Issue by huyz** [elixirkoans/elixir-koans#169]
The [koan](https://github.com/elixirkoans/elixir-koans/blob/master/lib/koans/10_map_sets.ex#L18-L20) that shows that MapSets aren't ordered is confusing:
```
koan "Even though I am like a list I am unordered after 32 elements" do
    assert 1..33 |> MapSet.new() |> Enum.fetch(0) == {___, 11}
end
```

There are two reasons:

1. "*after* 32 elements" is grammatically misleading and the number 32 is unexplained.
1. It's unclear to beginners where the number 11 comes from.  For those who understand where the 11 could come from (some incidental determinism?), it seems that this koan is brittle as there's no guarantee that the runtime would put this item in the beginning (I assume).

**Comment by iamvery** [comment]
Closed by #174
