### ISSUE TITLE
About koan "I think I need my number as a char"

### ISSUE THREAD

**Issue by Nagasaki45** [elixirkoans/elixir-koans#176]
The concept of char lists was not presented before this koan. Strings, however, were already presented.
I think that this specific koan imposible to grasp without start googling for char lists and the special way they are defined in elixir (compared to python, my main language, for example).
Maybe it is too early to present it or there is a need to present some related concepts before. What do you think?

**Comment by felipesere** [comment]
Sounds interesting! I don't consciously use char lists very often, so I didn't even notice.
Do you have suggestions what an alternative could be? Might the koan not be relevant at all?

@ukutaht @iamvery @marosluuce @Maikon @gemcfadyen @nickbdyer How often do you use char lists?

**Comment by Nagasaki45** [comment]
Yes, droping this koan altogether is not a bad idea. I'm relatively new to elixir, so I can't tell how important is this concept, but it is generally confusing.

**Comment by felipesere** [comment]
@Nagasaki45 open a PR to remove it 😄
