### ISSUE TITLE
elixir-koans not supported for elixir 1.5.0

### ISSUE THREAD

**Issue by vinitgarg27** [elixirkoans/elixir-koans#177]
I cloned latest elixir from git repo and while running command "mix meditate" it shows this error : 
** (Mix) You're trying to run :elixir_koans on Elixir v1.5.0-dev but it has declared in its mix.exs file it supports only Elixir >= 1.2.1 and <= 1.4.1

Can anyone please help ?

**Comment by VitaliZaharenko** [comment]
Same too, when i changed mix.es, and put elixir: ">= 1.2.1 and <= 1.5.0". It gives: ** (CompileError) lib/koans/16_tasks.ex:6: unbound variable _
    (stdlib) lists.erl:1238: :lists.map/2
    (stdlib) lists.erl:1238: :lists.map/2

**Comment by iamvery** [comment]
We probably need to loosen up the Elixir versions covered by the project. See #167. It probably makes sense for the upper limit to be `~>1.4` which would cover all minor versions of 1.x
