### ISSUE TITLE
Hard to understand the purpose of atoms

### ISSUE THREAD

**Issue by Nagasaki45** [elixirkoans/elixir-koans#185]
I think that with the current atoms koan (`05_atoms.ex`) it is hard to understand the purpose of them. OK, they're "like strings", but what shoud we do with them. The fact that `true`, `false`, and modules (which were'nt instroduced yet, BTW) are atoms is even more confusing.

First, if we want to compare atoms to something it might be better to compare them to enums (like C enums).
Second, I think that instead of being correct, as with the last two atom koans (the ones about modules), we can just state that atoms are only equal to themselves, give a naive example, and move on.

**Comment by ukutaht** [comment]
Very good points. After reading this, and looking at the koans themselves they do feel more like a trivia quiz than a learning exercise.

I like the comparison with enums. This might be a detail not worth mentioning, but one purpose of atoms, as far as I can tell, is that they take less memory and are faster to equality-check than strings. Do you think we should include that as well?

**Comment by Nagasaki45** [comment]
Take a look at official [getting started](http://elixir-lang.org/getting-started/basic-types.html#atoms) tutorial. I think that it explains the concept well in the first sentence: "Atoms are constants where their name is their own value". Using the term "constant" is probably better than comparing them to enything (strings and enums).

I think that we can change the description of the first koan to follow this terminology. Then, keep only the first and the currently 3rd koans. The rest can be removed. I will open a PR shortly.

What do you think?

**Comment by ukutaht** [comment]
Agreed. A constant is a much better term here. Looking forward to the PR.

**Comment by Nagasaki45** [comment]
One more thing. We also have `nil`. Similar to the boolean values it is also an atom. Do you want to add this?

**Comment by ukutaht** [comment]
Yeah, sounds good :+1:

**Comment by Nagasaki45** [comment]
The PR is ready #189.
