### ISSUE TITLE
Make sure the runner and filenames agree on koans order

### ISSUE THREAD

**Issue by Nagasaki45** [elixirkoans/elixir-koans#196]
I open this issue in response to https://github.com/elixirkoans/elixir-koans/pull/194. It's a good catch of a a trivial bug we missed in https://github.com/elixirkoans/elixir-koans/pull/192, when we changed the order of the koans (the filenames) without changing the order of the modules in `runner.ex`.

As I see it, to make sure we don't mess this up again we have two options:
1. Have a test that validate the filenames against the order of the modules in `runner.ex`.
2. Make `runner.ex` build the order from the order of the filenames.

If you have other suggestions do tell.
I will be happy to (try to) implement a solution with either approach.

**Comment by membranepotential** [comment]
It seems most natural too me to scan the folder with the koans, parse the filenames and build the module list from there. Maybe with an additional test to enforce naming conventions. The koan source files are already sort of driving the state of the app, so I think it makes most sense to encode the order in this place.

**Comment by Nagasaki45** [comment]
I tried to take this path, of building the list of modules to run from the order of the files, but found it way more complicated than I thought. We will need to either to:

1. Go over each file, read the source code, compile it, and get the "main" module out. Some relevant material [here](http://stackoverflow.com/q/13223238/1224456).
2. Hack a simpler solution by reading the first line of each file and extracting the module name with regex.
3. Go the other way around, and check for each loaded module the path of the source file (see [here](http://stackoverflow.com/q/28664119/1224456)), filter them out base on the directory, and sort by filename.

I don't think that any of the options above is good, and start to prefer a test for making sure the order in `runner.ex` match the order of the filenames instead, which will hopefully be simpler to do. But maybe I'm missing something obvious, does anyone have an elegant solution in mind?

**Comment by membranepotential** [comment]
I wouldn't know if there was a more elegant solution, but I suppose simpler is better.

I guess the module name could be parsed from the file name, but the unnecessary complexity of dynamically loading the module remains.

**Comment by Nagasaki45** [comment]
Guessing the module name from the file name is dangerous. Let's assume a module named `HTTP` in a file named `http.ex`. The naive but wrong parsing will be `Http`.

**Comment by felipesere** [comment]
I think we could try to use `application.get_key(:the_application_name, :modules)` to get all the modules in :the_application_namespace. I haven't tried it though. We could then sort that list by matching it up with its filename... 

It might be worth an experiment 😃

**Comment by felipesere** [comment]
`:application.get_key(:elixir_koans, :modules)` gave me very interesting results. We might have to namespace the koans better, for example, `defmodule Koans.Strings do` to be able to separate them from other modules. It looks promising.

**Comment by Nagasaki45** [comment]
Looks promising indeed! I don't think we need to namespace the koans differently just because of this. Instead, we can do something like this:

```elixir
{:ok, modules} = :application.get_key(:elixir_koans, :modules)
paths = Enum.map(modules, &(&1.module_info |> get_in([:compile, :source])))
```
Then zip them, filter by matching to `File.cwd() <> "lib/koans/" <> filename`, and sort.

I will send a PR in the next few days.
Thanks for the input!

**Comment by Nagasaki45** [comment]
Another issue :-(
We already have some source file that contain more then one module. For example, in `lib/koans/18_protocols.ex` we have:

```elixir
[
  Protocols,
  Protocols.Baker,
  Protocols.Dancer,
  Protocols.Musician,
  Protocols.School.Any,
  Protocols.School.Protocols.Dancer,
  Protocols.School.Protocols.Musician,
  Protocols.School.Protocols.Student,
  Protocols.Student,
]
```
We can decide that we will always use modules without `.` in their name (converting the atom to string and check). However, we might want in the future to have some heirarchy for the koans, for example, we might introduce `OTP` koans, and we will have lessons like `OTP.GenServer`, `OTP.Supervisor`, `OTP.Application`. In this case it will get really messy.

I'm sorry I'm doing this, but I need your advice again to get this one further without doing too much mess.

**Comment by felipesere** [comment]
Hmm... Our modules have a function called `all_koans()` that returns a list of koan functions. You could try calling that and rescuing if it fails? Otherwise we can [register an attribute](https://hexdocs.pm/elixir/Module.html#register_attribute/3) and [look for it later](https://hexdocs.pm/elixir/Module.html#get_attribute/2). For registering you'll have to modify the `koan` macro
