### ISSUE TITLE
Concepts appear in lesson 7 without proper introduction

### ISSUE THREAD

**Issue by Nagasaki45** [elixirkoans/elixir-koans#203]
I found two concepts that appear in lesson 7 before they are properly introduced.

- The `if` macro.
- Anonymous functions defined with `fn`.

I don't know how unclear these examples are for someone that is new to the language (or new to programming in general). Good chances that I'm just nit picking and everything is fine. However, in the case of `if` we might want to introduce it on an earlier lesson, like in the numbers or atoms lessons. I think that it will be better to simplify the exercise with `fn` not to use this concept.

Will be happy to provide a PR. What do you think?

**Comment by felipesere** [comment]
I have rearranged some of the koans in #215 
Amongst other things, I move the koan that used both `fn` and `if` to the function koans, as it was more about using keyword lists _as arguments_.
Happy to see PRs for further improvements! 💙
