### ISSUE TITLE
Suggestion: 10_structs.ex

### ISSUE THREAD

**Issue by CodyStringham** [elixirkoans/elixir-koans#214]
First comment, this is an awesome project. That being said there is an entry on `10_structs.ex` on line `60` that doesn't make sense.

Up to this point functions have not been covered, let alone the `&` capture operator has not been shown or explained which to someone new will be very confusing. I think you should revisit this and and use something like:

```
fn x -> x + 2 end
```

Either way great job.

**Comment by Nagasaki45** [comment]
+1

This is a  similar issue to #203, so we might want to solve them together.

**Comment by felipesere** [comment]
Thank you both for bringing this up 🙂👍
Would you suggest introducing fn/&-notation first or rewriting this example?
