### ISSUE TITLE
Should `===` be used for differentiating floats and ints?

### ISSUE THREAD

**Issue by Cohen-Carlisle** [elixirkoans/elixir-koans#216]
Here's the example that made me think this might be a good idea in some cases:
https://github.com/elixirkoans/elixir-koans/blob/18ce1752d45c9069905e31f3e67ad79259edc1d2/lib/koans/03_numbers.ex#L52-L54
`assert Float.ceil(34.25) == 35` would pass this test, even though `Float.ceil/1` produces a float.

**Comment by iamvery** [comment]
I feel like the example would be more confusing with `===` as it would explicitly require the learner to specify a decimal despite the description reading "I don't want this decimal point". I think the forgiving nature of `==` is exactly what the example encourages. What do you think?

**Comment by Cohen-Carlisle** [comment]
Hmm, I thought the title was referring to dropping the precision of the decimal, not the presence of any decimal (because it is a float and hence still has a decimal). I think if `===` is introduced, it should probably be in a new koan, though.

**Comment by iamvery** [comment]
Maybe we're saying the same thing?

If there isn't a koan that covers `===`, I think that would be a great addition!

@felipesere @ukutaht do you agree with the above conversation?

**Comment by Cohen-Carlisle** [comment]
> Maybe we're saying the same thing?

Yes, I think so. Originally, I was thinking existing koans should be modified. But now I think it would make more sense to add koans around `===`.

**Comment by iamvery** [comment]
Do it! Would love to see what you come up with 🎉
