### ISSUE TITLE
Question on Patern Matching

### ISSUE THREAD

**Issue by mingyar** [elixirkoans/elixir-koans#261]
Hi! Could someone help me on that?

I'm trying to solve that one, it seems to be right but is not passing:

The original code is:
```
koan "Lists must match exactly" do
    assert_raise ___, fn ->
      [a, b] = [1, 2, 3]
    end
  end  
```

And I'm trying that:

```
koan "Lists must match exactly" do
    assert_raise ___, fn ->
      [a, b, c] = [1, 2, 3]
    end
  end
```  

Then the output is like "still the same":

> Lists must match exactly
> Assertion failed in lib/koans/12_pattern_matching.ex:42
> assert_raise(___, fn -> [a, b, c] = [1, 2, 3] end)

  
Maybe I'm not understanding that structure calling an anonymous function.  

I already had tested on my terminal doing just:

`
[a, b, c] = [1, 2, 3]
`

And it seems to be right.

**Comment by iamvery** [comment]
@mingyar the general pattern for the koans is to replace the `___` with an answer/solution, so in this case, it's trying to teach you the error that is raised by the body of the function. Does that help?

**Comment by mingyar** [comment]
@iamvery Gotcha!

So do I need just to provide the correct exception name at ___, right?

**Comment by iamvery** [comment]
You got it 👍 Leave the other code unchanged, `[a,b] = [1,2,3]`

**Comment by mingyar** [comment]
@iamvery I tried to fix:

```
koan "Lists must match exactly" do
    assert_raise "MatchError (no match of right hand side value: [1, 2, 3])", fn ->
      [a, b] = [1, 2, 3]
    end
  end

```
But it seems still no pass:

Now meditate upon PatternMatching
|================> | 119 of 209

Lists must match exactly
Assertion failed in lib/koans/12_pattern_matching.ex:44
Expected exception “MatchError (no match of right hand side value: [1, 2, 3])” but got MatchError (no match of right hand side value: [1, 2, 3])

**Comment by mingyar** [comment]
Ok.

Just solved doing:

koan "Lists must match exactly" do
    assert_raise MatchError, "no match of right hand side value: [1, 2, 3]", fn ->
      [a, b] = [1, 2, 3]
    end
end

Thanks for helping

**Comment by iamvery** [comment]
Glad you worked it out :)
