### ISSUE TITLE
Match failure in 15_processes.ex - ex_unit_no_meaningful_value

### ISSUE THREAD

**Issue by briankung** [elixirkoans/elixir-koans#266]
Something isn't matching in Processes 173
Here's my code:

```elixir
koan "A common pattern is to include the sender in the message, so that it can reply" do
  greeter = fn ->
    receive do
      {:hello, sender} -> send(sender, :how_are_you?)
    end
  end

  pid = spawn(greeter)

  send(pid, {:hello, self()})
  assert_receive :how_are_you
end
```

And here's what I get:

```
Now meditate upon Processes
|========================>     | 173 of 209
----------------------------------------
A common pattern is to include the sender in the message, so that it can reply
Assertion failed in lib/koans/15_processes.ex:80
assert_receive(:how_are_you)

left:  :how_are_you
right: :ex_unit_no_meaningful_value
```

Interestingly, even if I change it to really forgiving match arms, it still gives me `:ex_unit_no_meaningful_value`:

```elixir
self_pid = self()
greeter = fn ->
  receive do
    _anything -> send(self_pid, :how_are_you?)
  end
end
```

I'm on macOS and Elixir version 1.12.2 with Erlang/OTP 24. Any help would be appreciated!

**Comment by iamvery** [comment]
Hey Brian, _very_ late reply here 😅 . Can you try this again? Some changes were made in #271 that may address the problem you were seeing.

**Comment by briankung** [comment]
Thanks for coming back to notify me! I've since moved on, but I'll try to run this when I get a chance.

**Comment by iamvery** [comment]
I see, it's because the value given to [`assert_receive`](https://hexdocs.pm/ex_unit/ExUnit.Assertions.html#assert_receive/3) is used for a match. Since the pattern match fails, you get a pretty crummy error message. I'll add a failure message to the call which may help clear it up. PR incoming

**Comment by briankung** [comment]
Wow, I had a question mark in there this whole time? 🤦‍♂️ thanks for the hint and the PR!
