### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zzz6519003** [elixirkoans/elixir-koans#283]
```elixir
  koan "Tuples can contain different things" do
    assert {:a, 1, "hi"} ==  {:a, 1, "hi"}
  end
```

i don't get it, does this have a point?

**Comment by felipesere** [comment]
Huh that should probably have a gap somewhere.
It's meant to highlight that you don't need to limit yourself to "just a tuple of integers/atoms/etc".
Maybe a remnant from my statically-typed brain 🧠

**Comment by zzz6519003** [comment]
maybe i think too much, thx for the work
