### ISSUE TITLE
Wrong ordering of Koans

### ISSUE THREAD

**Issue by Kit-Ko** [elixirkoans/elixir-koans#91]
After running mix meditate, the koans starts with 10_processes.ex instead of 01_equalities.ex in ubuntu linux 15.10.

EDIT: no problem with ubuntu 16.04

**Comment by felipesere** [comment]
Thank you for reporting this! I will look into it.

**Comment by alexandru-calinoiu** [comment]
Running just fine here on OpenSuse

**Comment by felipesere** [comment]
Is this still an issue or has it resolved over time?

**Comment by Kit-Ko** [comment]
I have switched to Apricity OS / Arch Linux and have no problem. 
I have no idea about the latest version of Ubuntu (16.10)
