### ISSUE TITLE
Autoreload doesn't work on macbook

### ISSUE THREAD

**Issue by marioosh** [elixirkoans/elixir-koans#96]
I'm trying to make koans, but it shows me an error every time I save the edited file:

    ** (Code.LoadError) could not load /sandbox/elixir_koans/elixir-koans/lib/koans/05_maps.ex___jb_tmp___
    (elixir) lib/code.ex:662: Code.find_file/2
    (elixir) lib/code.ex:319: Code.load_file/2

I have Macbook Pro with Retina 2015, fresh installed, the newest Elixir(1.2.4) from Homebrew

**Comment by marioosh** [comment]
I pulled into new folder and now it works, weird :/

**Comment by marioosh** [comment]
Reopened: This issue is present when file is edited in IntelliJ IDEA with Elixir plugin.

**Comment by ukutaht** [comment]
Thanks for reporting. It seems like IntelliJ is writing some temp files into the watched directory which the runner doesn't expect. We're looking into this

**Comment by felipesere** [comment]
@marioosh can you pull the branch with `git fetch origin pull/102/head:intellij-fix && git checkout intellij-fix` and retry?

**Comment by marioosh** [comment]
Works great !!!

2016-05-04 22:56 GMT+02:00 Felipe Seré <notifications@github.com>:

> @marioosh <https://github.com/marioosh> can you pull the branch with git
> fetch origin pull/102/head:intellij-fix && git checkout intellij-fix and
> retry?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixirkoans/elixir-koans/issues/96#issuecomment-217000288>
>



-- 
Mariusz Nosiński
507-183-661
mnosinski@gmail.com
